[package]
name = "book-api"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
rocket = "0.4.6"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["json"]
